version: "3.8"

services:
    app:
        build: .
        container_name: assembly_endgame
        ports:
            - "5173:5173"
        volumes:
            - .:/app
            - /app/node_modules
        command: npm run dev
